"use client";
import { createContext, useContext } from "react";

export const LIGHT = {
  appBg:          "#eef0f4",
  surface:        "#ffffff",
  surface2:       "#f5faf6",
  headerBg:       "#1a5e35",
  sidebarBg:      "#ffffff",
  sidebarBorder:  "#eeeeee",
  navLabel:       "#bbbbbb",
  navText:        "#555555",
  navActiveBg:    "#1a5e35",
  navActiveText:  "#ffffff",
  text:           "#111111",
  text2:          "#444444",
  text3:          "#888888",
  border:         "#c3dfc9",
  border2:        "#dddddd",
  calBg:          "#f5faf6",
  calText:        "#444444",
  cardBg:         "#ffffff",
  cardBorder:     "#dddddd",
  tableHead:      "#999999",
  tableRow:       "#ffffff",
  tableRowSel:    "#f0faf3",
  tableRowBorder: "#f3f3f3",
  dispenseCard:   "#eef7f1",
  notifBg:        "#ffffff",
  notifBorder:    "#eeeeee",
  notifText:      "#333333",
  notifText2:     "#555555",
  modalBg:        "#ffffff",
  modalText:      "#222222",
  modalText2:     "#444444",
  inputBorder:    "#cccccc",
  readonlyBg:     "#f5f5f5",
  green:          "#1a5e35",
  greenLight:     "#2d9e58",
  profileBg:      "#ffffff",
  profileText:    "#222222",
};

export const DARK = {
  appBg:          "#0d1f14",
  surface:        "#132b1c",
  surface2:       "#0f2318",
  headerBg:       "#0b1f10",
  sidebarBg:      "#132b1c",
  sidebarBorder:  "#1e3d28",
  navLabel:       "#4a7a5a",
  navText:        "#8ab89a",
  navActiveBg:    "#1a5e35",
  navActiveText:  "#ffffff",
  text:           "#e8f5ec",
  text2:          "#b0cfba",
  text3:          "#6a9a7a",
  border:         "#2a5a3a",
  border2:        "#1e3d28",
  calBg:          "#0f2318",
  calText:        "#8ab89a",
  cardBg:         "#132b1c",
  cardBorder:     "#1e3d28",
  tableHead:      "#4a7a5a",
  tableRow:       "#132b1c",
  tableRowSel:    "#1a3a25",
  tableRowBorder: "#1e3d28",
  dispenseCard:   "#0f2318",
  notifBg:        "#132b1c",
  notifBorder:    "#1e3d28",
  notifText:      "#e8f5ec",
  notifText2:     "#8ab89a",
  modalBg:        "#132b1c",
  modalText:      "#e8f5ec",
  modalText2:     "#b0cfba",
  inputBorder:    "#2a5a3a",
  readonlyBg:     "#0f2318",
  green:          "#1a5e35",
  greenLight:     "#2d9e58",
  profileBg:      "rgba(255,255,255,0.1)",
  profileText:    "#ffffff",
};

export type Theme = typeof LIGHT;

export const ThemeCtx = createContext<{ t: Theme; dark: boolean; toggle: () => void }>({
  t: LIGHT, dark: false, toggle: () => {},
});

export const useTheme = () => useContext(ThemeCtx);
