// utils/auditLogs.ts
// ─────────────────────────────────────────────────────────────────────────────
// Canonical audit-logging helper for SMARTRHU.
//
// Records every tracked user action into the `audit_logs` table so the
// System Activities (Audit Trail) page can display them. Logs are
// auto-generated by the system and are never edited/deleted by users.
//
// SUPABASE TABLE (run once in the SQL editor). Note the two added columns
// `patient_name` and `reference_id` used by the audit page:
//
//   CREATE TABLE IF NOT EXISTS audit_logs (
//     id            uuid DEFAULT gen_random_uuid() PRIMARY KEY,
//     user_id       uuid REFERENCES auth.users(id),
//     user_name     text,
//     user_role     text,
//     action        text NOT NULL,          -- e.g. 'Send prescription'
//     module        text,                   -- e.g. 'Prescription'
//     description   text,                    -- e.g. 'Sent prescription to Juan Dela Cruz'
//     patient_name  text,                    -- optional, shown in its own column
//     reference_id  text,                    -- optional transaction / record id
//     status        text DEFAULT 'success',  -- success | completed | pending | warning | failed
//     ip_address    text,
//     created_at    timestamptz DEFAULT now()
//   );
//
//   -- Recommended index for fast descending reads:
//   CREATE INDEX IF NOT EXISTS audit_logs_created_at_idx ON audit_logs (created_at DESC);
//
// USAGE (preferred object form):
//   await logAction({
//     user_name: user?.name, user_role: user?.role,
//     action: 'Send prescription', module: 'Prescription',
//     description: `Sent prescription to ${name}`,
//     patient_name: name, reference_id: rxId, status: 'success',
//   })
//
// USAGE (legacy positional form — still supported so older calls don't crash):
//   await logAction('Dispensed medicine', 'Pharmacy', 'pharmacist')
// ─────────────────────────────────────────────────────────────────────────────
import { supabase } from "@/lib/supabase";

export type AuditStatus =
  | "success"
  | "completed"
  | "pending"
  | "warning"
  | "failed"
  | "error";

export interface LogActionParams {
  user_name?: string;
  user_role?: string;
  action: string;
  module?: string;
  description?: string;
  patient_name?: string | null;
  reference_id?: string | null;
  status?: AuditStatus | string;
  ip_address?: string | null;
}

/**
 * Insert an audit-trail record.
 *
 * Accepts either an object (preferred) or positional args
 * (action, module, role) for backward compatibility with existing call sites.
 * Never throws — logging must never break the action it is recording.
 */
export async function logAction(
  params: LogActionParams | string,
  module?: string,
  role?: string
): Promise<void> {
  try {
    const row: LogActionParams =
      typeof params === "string"
        ? { action: params, module: module ?? "", user_role: role ?? "" }
        : params;

    if (!row.action) return;

    // Base payload — always-present columns.
    const payload: Record<string, any> = {
      user_name: row.user_name || "System",
      user_role: row.user_role || "—",
      action: row.action,
      module: row.module || null,
      description: row.description || null,
      status: row.status || "success",
      ip_address: row.ip_address ?? null,
      created_at: new Date().toISOString(),
    };

    // Only attach optional columns when supplied, so the insert still works
    // on installations that haven't added patient_name / reference_id yet.
    if (row.patient_name !== undefined) payload.patient_name = row.patient_name;
    if (row.reference_id !== undefined) payload.reference_id = row.reference_id;

    const { error } = await supabase.from("audit_logs").insert(payload);
    if (error) console.warn("logAction insert failed:", error.message);
  } catch (e) {
    console.warn("logAction failed:", e);
  }
}

export default logAction;